data_ingestion:
  test_size: 0.2
  random_state: 42

feature_engineering:
  max_features: null

train:
  logistic_regression:
    C: 0.06
    penalty: l2
    solver: liblinear

model:
  model_version: 9