name: CI

on: push

jobs:
  project-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run DVC Pipeline
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: dvc repro
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build the docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/emotion-detection-final:latest .

      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/emotion-detection-final:latest

  deploy-on-ec2:
    needs: project-pipeline
    runs-on: self-hosted

    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull the docker image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/emotion-detection-final:latest

      - name: Stop current containers
        continue-on-error: true
        run: docker stop emotion-detection
      
      - name: Remove pre-existing containers
        continue-on-error: true
        run: docker container rm emotion-detection
        
      - name: Run the container
        run: docker run --name emotion-detection -p 80:8000 -d -e DAGSHUB_USER_TOKEN=${{ secrets.DAGSHUB_TOKEN }} ${{ secrets.DOCKERHUB_USERNAME }}/emotion-detection-final:latest


